export const actionTypes = {
  ADD_CARD_DATA: "ADD_CARD_DATA",
  DELETE_CARD_DATA: "DELETE_CARD_DATA",
  EDIT_CARD_DATA: "EDIT_CARD_DATA",
  SELECTED_CARD_DATA: "SELECTED_CARD_DATA",
  COPY_CARD_DATA: "COPY_CARD_DATA",
};
